


























/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f4537b-2582ac346cc6005a6713bfc1;3c59ab6f-82bd-4cb9-b6e3-b3631c6993e2)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(
{'train_runtime': 63.8334, 'train_samples_per_second': 3.446, 'train_steps_per_second': 0.423, 'train_loss': 1.6195280287000868, 'epoch': 0.98}
***** train metrics *****
  epoch                    =     0.9818
  total_flos               =  3543966GF
  train_loss               =     1.6195
  train_runtime            = 0:01:03.83
  train_samples            =        220
  train_samples_per_second =      3.446
  train_steps_per_second   =      0.423
15
1.2e-06


























/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f453b5-268e4d6564d8282a738bf8c4;16270b4e-56b2-4713-a1db-1b2817118848)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(
  0%|                                                                                                                   | 0/28 [00:00<?, ?it/s]
{'train_runtime': 56.4427, 'train_samples_per_second': 3.862, 'train_steps_per_second': 0.478, 'train_loss': 1.6107389662000868, 'epoch': 0.99}
***** train metrics *****
  epoch                    =     0.9908
  total_flos               =  3543966GF
  train_loss               =     1.6107
  train_runtime            = 0:00:56.44
  train_samples            =        218
  train_samples_per_second =      3.862
  train_steps_per_second   =      0.478
16



























/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f453f1-4526151735e9956c00b489b0;8a11990c-5a3b-4a1e-ab49-2e861d879619)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(
  0%|                                                                                                                   | 0/27 [00:00<?, ?it/s]
{'train_runtime': 58.7741, 'train_samples_per_second': 3.828, 'train_steps_per_second': 0.476, 'train_loss': 1.6055991309029716, 'epoch': 0.99}
***** train metrics *****
  epoch                    =     0.9912
  total_flos               =  3675224GF
  train_loss               =     1.6056
  train_runtime            = 0:00:58.77
  train_samples            =        225
  train_samples_per_second =      3.828
  train_steps_per_second   =      0.476
15


























/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f4542b-4482fd2651a7e98e746cea7a;a23332ee-1d63-4f04-80fb-8488409cf192)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(
  0%|                                                                                                                   | 0/27 [00:00<?, ?it/s]
{'train_runtime': 56.9345, 'train_samples_per_second': 3.899, 'train_steps_per_second': 0.474, 'train_loss': 1.615110609266493, 'epoch': 0.97}
***** train metrics *****
  epoch                    =      0.973
  total_flos               =  3543966GF
  train_loss               =     1.6151
  train_runtime            = 0:00:56.93
  train_samples            =        222
  train_samples_per_second =      3.899
  train_steps_per_second   =      0.474
15


























 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████    | 26/27 [00:54<00:02,  2.10s/it]
{'train_runtime': 56.8177, 'train_samples_per_second': 3.872, 'train_steps_per_second': 0.475, 'train_loss': 1.6264449225531683, 'epoch': 0.98}
***** train metrics *****
  epoch                    =     0.9818
  total_flos               =  3543966GF
  train_loss               =     1.6264
  train_runtime            = 0:00:56.81
  train_samples            =        220
  train_samples_per_second =      3.872
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/other.py:611: UserWarning: Unable to fetch remote file due to the following error 403 Client Error. (Request ID: Root=1-67f45465-5b60275a40beb74e14fef478;0bc09dad-23fa-422e-b434-aee2a918ad95)
Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-3B/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-3B is restricted and you are not in the authorized list. Visit https://huggingface.co/meta-llama/Llama-3.2-3B to ask for access. - silently ignoring the lookup for the file config.json in meta-llama/Llama-3.2-3B.
  warnings.warn(
/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/peft/utils/save_and_load.py:195: UserWarning: Could not find a config file in meta-llama/Llama-3.2-3B - will assume that the vocabulary was not modified.
  warnings.warn(












  File "/data/home/yjw5427/translora/fed_lora.py", line 934, in <module>███████████████████████████████████████| 32/32 [00:23<00:00,  1.57it/s]
    main()
  File "/data/home/yjw5427/translora/fed_lora.py", line 828, in main
    metrics = trainer.evaluate()
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/transformers/trainer.py", line 3868, in evaluate
    output = eval_loop(
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/transformers/trainer.py", line 4160, in evaluation_loop
    metrics = self.compute_metrics(EvalPrediction(predictions=all_preds, label_ids=all_labels))
  File "/data/home/yjw5427/translora/fed_lora.py", line 687, in compute_metrics
    valid_idx = [i for i, pred in enumerate(extracted_preds) if pred is not None]
UnboundLocalError: local variable 'extracted_preds' referenced before assignment
Traceback (most recent call last):
  File "/data/home/yjw5427/translora/fed_lora.py", line 934, in <module>
    main()
  File "/data/home/yjw5427/translora/fed_lora.py", line 828, in main
    metrics = trainer.evaluate()
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/transformers/trainer.py", line 3868, in evaluate
    output = eval_loop(
  File "/home/yjw5427/miniconda3/envs/trans/lib/python3.10/site-packages/transformers/trainer.py", line 4160, in evaluation_loop
    metrics = self.compute_metrics(EvalPrediction(predictions=all_preds, label_ids=all_labels))
  File "/data/home/yjw5427/translora/fed_lora.py", line 687, in compute_metrics
    valid_idx = [i for i, pred in enumerate(extracted_preds) if pred is not None]
UnboundLocalError: local variable 'extracted_preds' referenced before assignment